- src/lib/package.json
aangepast: versie update van src/lib
> AGL-2694: Stijldefinities

- src/lib/kaart/kaart-achtergrond-selector.component.scss
- src/lib/kaart/kaart-achtergrond-selector.component.ts
- src/lib/kaart/kaart-achtergrond-tile.component.scss
- src/lib/kaart/kaart-protocol-events.ts
aangepast: plaatsing meer in lijn met material design
aangepast: code in commentaar verwijderd
> AGL-2801: styling van selector

- src/lib/kaart/kaart-laag.component.ts
- src/lib/kaart/kaart-reducer.ts
aangepast: lagen voor kaart-classic in goede volgorde toevoegen.
> AGL-2801: Lagen tonen en verbergen

- src/lib/kaart/kaart-protocol-events.ts
- src/lib/kaart/kaart-reducer.ts
- src/lib/kaart/kaart-with-info.ts
- src/lib/kaart/laag-converter.ts
aangepast: de blancolaag is nu een echte laag
aangepast: laadbaar -> mag getoond worden
> AGL-2810: Lagen ordenen

- src/lib/kaart/kaart-protocol-events.ts
- src/lib/kaart/kaart-reducer.ts
- src/lib/kaart/kaart-with-info.ts
- src/testApp/app.component.html
- src/testApp/app.component.ts
aangepast: de z-index word gebruikt om lagen boven elkaar te
plaatsen.
aangepast: de lagen worden niet meer opgeslagen in een map naar
Option<Layer>, maar een map van <Layer> direct.
> AGL-2810: Z-index grebruiken

- src/testApp/app.component.html
- src/testApp/app.module.ts
- src/testApp/av-kaart-inner.component.html
- src/testApp/av-kaart-inner.component.ts
- src/testApp/av-kaart.component.html
- src/testApp/av-kaart.component.ts
Een voorbeeld in aparte html dat zo goed mogelijk overeenstemt met het gebruik van de kaartcomponent in AV
> voorbeeld kaart zoals in AdviezenEnVergunningen

- package.json
- src/lib/google-locatie-zoeker/google-locatie-zoeker.service.ts
- src/lib/kaart/kaart-child-component-base.ts
- src/lib/kaart/laag-converter.ts
- src/lib/kaart/subscription-helper.ts
Fix TS compiler warnings
laatste openlayers versies
fix olx
> Add missing constructor

- src/lib/kaart/index.ts
- src/lib/kaart/kaart-protocol-commands.ts
- src/lib/kaart/kaart-protocol-subscriptions.ts
- src/lib/kaart/kaart-with-info.ts
aangepast: imports bijgewerkt. TypescriptHero was iets te
overijverig.
> AGL-2656: Locatiezoeker

- src/lib/kaart/kaart-reducer.ts
aangepast: ontbrekende subscription gelogd
aangepast: betere naam voor hulpfunctie
> AGL-2878: Subscriptions loggen

- src/lib/kaart/kaart-achtergrond-selector.component.ts
- src/lib/kaart/kaart-internal-messages.ts
- src/lib/kaart/kaart-reducer.ts
- src/lib/kaart/kaart-with-info-model.ts
- src/lib/kaart/kaart-with-info.ts
- src/lib/kaart/kaart.component.ts
- src/lib/kaart/model-changes.ts
- src/lib/lagenkiezer/lagenkiezer.component.ts
aangepast: de modelchanger moet uniek zijn per kaart. Duh!
aangepast: wegwerken van internal messages voor lagen en grote
replaybuffer.
> AGL-2874: Lagenkiezer Naar NgKaart

- src/lib/kaart/kaart-protocol-subscriptions.ts
- src/lib/kaart/kaart-reducer.ts
- src/lib/kaart/model-changes.ts
toegevoegd: Er is nu een specifieke event voor het verwijderen van lagen.
> AGL-2874: Bug fix voor lagen verwijderen

- src/testApp/app.component.html
- src/testApp/app.component.ts
aangepast: foutje in demo pagina: kon kaartselectie niet ongedaan
maken.
> AGL-2898: @Input voor geselecteerde features

- src/lib/classic/index.ts
- src/lib/classic/streetview/classic-streetview.component.ts
- src/lib/classic/zoom/classic-zoom.component.ts
- src/lib/kaart/kaart.component.html
- src/lib/kaart/mijn-locatie/kaart-mijn-locatie.component.ts
- src/lib/kaart/open-street-view/kaart-open-street-view.component.ts
- src/lib/kaart/zoom/kaart-zoom.component.ts
- src/testApp/app.component.html
- src/testApp/app.component.ts
- zoom optioneel
- streetview optioneel
- test-app uitgebreid
> AGL-2956 zoom en streetview optioneel maken

- src/lib/classic/common/classic-ui-element-selector-component-base.ts
- src/lib/classic/index.ts
- src/lib/classic/streetview/classic-streetview.component.ts
- src/lib/classic/zoeker/classic-zoeker.component.ts
- src/lib/classic/zoom/classic-zoom.component.ts
- src/lib/kaart/kaart.component.html
- src/lib/zoeker/box/zoeker-box.component.ts
- src/testApp/app.component.html
- src/testApp/app.component.ts
- zoeker optioneel gemaakt
- UiElementOpties default een lege hash laten teruggeven
- imports in index.ts gegroepeerd en alfabetisch gezet
> AGL-2969 zoeker optioneel gemaakt

- src/lib/classic/lagen/classic-features-laag.component.ts
- src/testApp/app.component.ts
aangepast: gebuik ngOnChanges ipv ngDoCheck voor performantie.
> AGL-2980: VervangFeaturesCmd te vroeg

- src/lib/kaart/kaart.component.ts
- src/lib/zoeker/box/zoeker-box.component.ts
- src/lib/zoeker/box/zoeker-box.html
- src/lib/zoeker/index.ts
- wis invoer en zoekresultaten via aparte knop in zoeker-box
- ook tooltips toegevoegd op alle knoppen in zoeker-box
- focus op zoekveld na wis invoer om snel terug nieuwe invoer te doen
- fix voor kaartLinksRefreshWeergave: initialisatie probleem waardoor de weergave niet klopte
> AGL-2874 wis invoer van zoekveld en zoekresultaten

- src/lib/zoeker/box/zoeker-box.component.html
- src/lib/zoeker/box/zoeker-box.component.scss
- src/lib/zoeker/box/zoeker-box.component.ts
- src/lib/zoeker/crab/zoeker-crab-getrapt.component.html
- src/lib/zoeker/crab/zoeker-crab-getrapt.component.scss
- src/lib/zoeker/crab/zoeker-crab-getrapt.component.ts
- src/lib/zoeker/perceel/zoeker-perceel-getrapt.component.html
- src/lib/zoeker/perceel/zoeker-perceel-getrapt.component.scss
- src/lib/zoeker/perceel/zoeker-perceel-getrapt.component.ts
- labels lichtjes anders
- maak leeg knop vervangen door 'close'-icon bovenaan zoals bij de gewone zoek
- label "toon op kaart" hernoemd naar "zoek"
> AGL-3054 kleine verbeteringen in 'Zoek op perceel' en 'Zoek op crab'

- src/lib/classic/kaart-classic.component.ts
- src/lib/coordinaten/coordinaten.service.ts
- src/lib/kaart/achtergrond-selector/kaart-achtergrond-selector.component.ts
- src/lib/kaart/index.ts
- src/lib/kaart/info-boodschappen/kaart-info-boodschap-kaart-bevragen.component.html
- src/lib/kaart/info-boodschappen/kaart-info-boodschap-kaart-bevragen.component.scss
- src/lib/kaart/info-boodschappen/kaart-info-boodschap-kaart-bevragen.component.ts
- src/lib/kaart/info-boodschappen/kaart-info-boodschap.component.ts
- src/lib/kaart/info-boodschappen/kaart-info-boodschappen.component.html
- src/lib/kaart/info-boodschappen/kaart-info-boodschappen.component.ts
- src/lib/kaart/kaart-bevragen/kaart-bevragen.component.ts
- src/lib/kaart/kaart-bevragen/kaart-bevragen.service.ts
- src/lib/kaart/kaart-bevragen/laaginfo.model.ts
- src/lib/kaart/kaart-protocol-commands.ts
- src/lib/kaart/kaart-reducer.ts
- src/lib/kaart/kaart-with-info-model.ts
- src/lib/kaart/kaart-with-info.ts
- src/lib/kaart/loading/kaart-loading.component.ts
- src/lib/kaart/model-changes.ts
- src/lib/lagenkiezer/lagenkiezer.component.ts
- src/lib/util/subject-update.ts
toegevoegd: externe WMS laag informatie tonen adhv dynamisch
toegevoegde query services.
aangepast: laag in InfoBoodschap werdt niet overal ingevuld.
aangepast: performantieverbeteringen voor de infoboodschappen.
aangepast: niet meer bevragen tijdens e.g. tekenen
aangepast: readonly toegevoegd bij interfaces
> AGL-3039: Externe WMS raadplegen

- src/lib/classic/kaart-classic.component.ts
- src/lib/kaart/info-boodschappen/kaart-info-boodschap-alert.component.ts
- src/lib/kaart/info-boodschappen/kaart-info-boodschap-identify.component.ts
- src/lib/kaart/info-boodschappen/kaart-info-boodschap-kaart-bevragen.component.html
- src/lib/kaart/info-boodschappen/kaart-info-boodschap.component.html
- src/lib/kaart/info-boodschappen/kaart-info-boodschap.component.scss
- src/lib/kaart/info-boodschappen/kaart-info-boodschap.component.ts
- src/lib/kaart/info-boodschappen/kaart-info-boodschappen.component.html
- src/lib/kaart/info-boodschappen/kaart-info-boodschappen.component.ts
- src/lib/kaart/kaart-with-info-model.ts
- src/lib/kaart/meten/kaart-meten.component.ts
toegevoegd: icoontjes voor de infoboodschappen.
> AGL-3110: Icoontjes

- package.json
- src/lib/package.json
aangepast: ng-kaart versie naar 4
aangepast: ng build heeft andere parameters nodig
> AGL-3241: Angular 6

- projects/ng-kaart/package.json
- projects/ng-kaart/src/lib/kaart/kaart-bevragen/kaart-bevragen.component.ts
- projects/ng-kaart/src/lib/kaart/kaart-modus-component.ts
- projects/ng-kaart/src/lib/kaart/kaart-protocol-commands.ts
- projects/ng-kaart/src/lib/kaart/kaart-reducer.ts
- projects/ng-kaart/src/lib/kaart/kaart-with-info.ts
- projects/ng-kaart/src/lib/kaart/model-changes.ts
- projects/ng-kaart/src/lib/kaart/open-street-view/kaart-open-street-view.component.ts
toegevoegd: afzetten van selectie wanneer streetview aktief is
aangepast: work-around voor identify op een beter niveau opgevangen
> AGL-3172-StreetviewBijGebiedsdekkendeFeatures: bug fix

- projects/ng-kaart/src/lib/classic/kaart-classic.component.ts
- projects/ng-kaart/src/lib/kaart/copyright/kaart-copyright.component.ts
- projects/ng-kaart/src/lib/kaart/info-boodschappen/kaart-info-boodschappen.component.ts
- src/app/feature-demo.component.html
- src/app/feature-demo.component.ts
toegevoegd: mogelijkheid om het weergeven van de infoboodschap voor
kaart bevragen te onderdrukken.
> CK-81: Geen bevragen info

- src/workbox/index.js
allow to ent plugins by the global vr ngKaartRoutePlugins
> ent plugins cacheFirst strategy

- projects/ng-kaart/src/lib/classic/index.ts
- projects/ng-kaart/src/lib/classic/zoeker/classic-crab-zoeker.component.ts
- projects/ng-kaart/src/lib/classic/zoeker/classic-google-zoeker.component.ts
- projects/ng-kaart/src/lib/classic/zoeker/classic-perceel-zoeker.component.ts
- projects/ng-kaart/src/lib/classic/zoeker/classic-single-zoeker.component.ts
- projects/ng-kaart/src/lib/classic/zoeker/classic-zoeker.component.ts
- src/app/feature-demo.component.html
toegevoegd: specifieke tags voor de std zoekers
> CK-114: Pin tonen configureerbaar

- projects/ng-kaart/src/lib/classic/lagen/classic-geoserver-laag.component.ts
- projects/ng-kaart/src/lib/classic/lagen/classic-ortho-laag.component.ts
- projects/ng-kaart/src/lib/classic/lagen/classic-tilecache-laag.component.ts
- projects/ng-kaart/src/lib/classic/lagen/classic-wms-laag.component.ts
- projects/ng-kaart/src/lib/coordinaten/coordinaten.service.ts
- projects/ng-kaart/src/lib/kaart/kaart-elementen.ts
- projects/ng-kaart/src/lib/kaart/laag-converter.ts
- src/app/feature-demo.component.html
aangepast: WMS lagen kunnen andere projecties dan Lambert instellen
aangepast: ook classic tags kunnen gebruik maken van andere projecties
> AGL-3512: Meer dan Lambert

- projects/ng-kaart/src/lib/classic/kaart-classic.component.ts
- projects/ng-kaart/src/lib/classic/lagen/classic-wms-laag.component.ts
- projects/ng-kaart/src/lib/kaart/kaart-bevragen/laaginfo.model.ts
- projects/ng-kaart/src/lib/util/progress.ts
- src/app/feature-demo.component.html
- src/app/feature-demo.component.ts
toegevoegd: @Output met resultaat van kaart bevragen
> CK-177: Info laag bevragen

- .editorconfig
- projects/ng-kaart/src/lib/css/kaart.component-common.scss
- projects/ng-kaart/src/lib/kaart/achtergrond-selector/kaart-achtergrond-selector.component.html
- projects/ng-kaart/src/lib/kaart/achtergrond-selector/kaart-achtergrond-selector.component.scss
- projects/ng-kaart/src/lib/kaart/achtergrond-selector/kaart-achtergrond-selector.component.ts
- projects/ng-kaart/src/lib/kaart/kaart.component.scss
Mobiele achtergronden lagen kiezer:
> CK-259: mobile achtergrondlagen kiezer

- package-lock.json
- package.json
- projects/ng-kaart/src/lib/kaart/kaart-protocol-commands.ts
- projects/ng-kaart/src/lib/kaart/kaart-reducer.ts
- projects/ng-kaart/src/lib/kaart/kaart-with-info.ts
- projects/ng-kaart/src/lib/util/maps.ts
aangepast: RxJs Subscriptions nt naar buitenwereld maar intern bijhouden
> ELNG-688: feature selectie

- projects/ng-kaart/src/lib/util/cachetiles.ts
Ik heb de nieuwe versie lokaal getest, dit lijkt goed te werken.
> ELNG-797 Make sure 'this' is defined in 'tileUrlFunction'
